papapt/forms.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired, Length


class SearchForm(Form):
    search = StringField('search', validators=[
                         DataRequired(), Length(
                                        max=100,
                                        message=(u'太长？太短？改一下关键词吧'))
                         ])

papapt/__init__.py
from flask import Flask
from celery import Celery
from flask_bootstrap import Bootstrap, WebCDN
from flask_wtf.csrf import CsrfProtect
from werkzeug.utils import import_string
from config import config, Config
from models import db


celery = Celery(__name__, broker=Config.CELERY_BROKER_URL)
bootstrap = Bootstrap()
csrf = CsrfProtect()

blueprints = [
            'papapt.views.home:home',
            'papapt.views.search:search',
            'papapt.views.rating_website:rating',
            'papapt.views.timeline:timeline',
            'papapt.views.schedule:ustv',
            'papapt.views.top:top',
            'papapt.views.errors:error',
            ]


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    app.extensions['bootstrap']['cdns']['jquery'] = \
        WebCDN('//cdn.bootcss.com/jquery/2.2.4/')
    app.extensions['bootstrap']['cdns']['bootstrap'] = \
        WebCDN('//cdn.bootcss.com/bootstrap/3.3.6/')
    db.init_app(app)
    csrf.init_app(app)
    celery.conf.update(app.config)

    for bp_path in blueprints:
        bp = import_string(bp_path)
        app.register_blueprint(bp)

    return app

papapt/views/errors.py
from flask import Blueprint, render_template


error = Blueprint('error', __name__)


@error.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

papapt/views/home.py
# coding: utf-8
import re
from flask import Blueprint, render_template, current_app, redirect, url_for, \
            g, flash
from datetime import datetime, timedelta
from ..forms import SearchForm
from ..models import SearchKeyword, SearchDate
from ..gadgets import save_keyword


home = Blueprint('home', __name__, static_folder='../static')


@home.before_app_request
def before_app_request():
    g.search_form = SearchForm()


def transfer_format(dt):
    return dt.strftime('%Y-%m-%d %H:%M:%S')


def get_hot_keywords():
    end = datetime.now()
    diff = timedelta(days=current_app.config['INDEX_KEYWORD_PERIOD'])
    start = transfer_format(end - diff)
    end = transfer_format(end)
    r = SearchKeyword.query.\
        join(SearchKeyword.dates).\
        filter(SearchDate.date.between(start, end)).\
        order_by(SearchKeyword.hit.desc())
    return r


@home.route('/')
def index():
    r = get_hot_keywords().\
                        limit(current_app.config['INDEX_MAX_KEYWORD']).\
                        distinct().\
                        all()
    return render_template('index.html', rows=r)


def find_id(keyword):
    found, website, site_id = False, None, None
    imdb = re.findall(r"imdb.+(tt\d+)", keyword)
    douban = re.findall(r"douban.+/(\d+)", keyword)
    if imdb or douban:
        found = True
        website = 'imdb' if imdb else 'douban'
        site_id = imdb[0] if imdb else douban[0]
    return found, website, site_id


def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"%s" % error)


@home.route('/search_query', methods=['POST'])
def search():
    if g.search_form.validate_on_submit():
        keyword = g.search_form.search.data
        found, website, site_id = find_id(keyword)
        if found:
            return redirect(url_for(
                                    'rating.by_site_id',
                                    website=website,
                                    site_id=site_id
                                    ))
        else:
            save_keyword(keyword)
            return redirect(url_for('search.result', keyword=keyword))
    else:
        flash_errors(g.search_form)
        return redirect(url_for('.index'))

papapt/views/rating_website.py
# coding: utf-8
from flask import Blueprint, render_template, redirect, url_for, Markup,\
            flash, request, jsonify
from ..models import db, Douban, Imdb
from ..gadgets import save_keyword, get_json, parse_info
from .. import celery


rating = Blueprint('rating', __name__)


@rating.route('/<website>/<site_id>')
def by_site_id(website, site_id):
    if check_id_valid(website, site_id):
        maybe_int_id = check_turn_int(website, site_id)
        model = get_site_model(website)
        r = model.query.filter_by(web_id=maybe_int_id).first()
        if r:
            save_keyword(site_id, website)
        return render_template(
                                'byid.html',
                                website=website,
                                site_id=site_id,
                                result=r
                                )
    else:
        flash(create_id_invaild_msg(website, site_id))
        return redirect(url_for('home.index'))


def check_turn_int(website, site_id):
    return int(site_id) if website == 'douban' else site_id


def create_id_invaild_msg(website, site_id):
    site_name = {'imdb': 'IMDb', 'douban': '豆瓣'}.get(website, 'error')
    msg = '提取的%s编号<mark>%r</mark>位数不对，检查一下吧。'\
        % (site_name, site_id.encode('utf-8'))
    return Markup(msg.decode('utf-8'))


def check_id_valid(website, site_id):
    if website == 'imdb':
        return len(site_id) == 9
    if website == 'douban':
        return 6 < len(site_id) < 9


def get_site_model(website):
    return globals()[website.title()]


def create_new_row(website, info):
    row = None
    model = get_site_model(website)
    row = model(info)
    return row


@celery.task(bind=True)
def json_task(self, website, site_id):
    print('new task {0.id}, args: {0.args!r}'.format(self.request))
    self.update_state(state='PROGRESS', meta={'current': 30})
    success, json = get_json(website, site_id)
    self.update_state(state='PROGRESS', meta={'current': 50})
    if success:
        info = parse_info(website, json)
        self.update_state(state='PROGRESS', meta={'current': 70})
        row = create_new_row(website, info)
        self.update_state(state='PROGRESS', meta={'current': 80})
        db.session.add(row)
        self.update_state(state='PROGRESS', meta={'current': 90})
        db.session.commit()
        return {'current': 100}
    else:
        return {'current': 1}


@rating.route('/kickoff', methods=['POST'])
def start_task():
    website = request.form['website']
    site_id = request.form['id']
    if website == 'douban':
        site_id = int(site_id)
    task = json_task.delay(website, site_id)
    return jsonify({}), 202, {'progress': url_for('.task_status', task_id=task.id)}


@rating.route('/spider_status/<task_id>')
def task_status(task_id):
    status_msg = {
            30: '捕捉蜘蛛成功',
            50: '蜘蛛织网中',
            70: '收集信息成功',
            80: '蜘蛛回途中',
            90: '写入数据库',
            100: '1秒后刷新'
            }
    task = json_task.AsyncResult(task_id)
    if task.state == 'PENDING':
        response = {
            'state': task.state,
            'current': 10,
            'status': '寻找空闲蜘蛛'
        }
    elif task.state != 'FAILURE':
        current = task.info.get('current', 0)
        status = status_msg.get(current, 'error')
        response = {
            'state': task.state,
            'current': current,
            'status': status
        }
        if current == 1:
            response['status'] = '网络好像有点问题，或者试试别个编号吧'
        elif current == 100:
            response['job_done_mark'] = 1
    else:
        response = {
            'state': task.state,
            'current': 0,
            'status': '蜘蛛被你玩坏了'
        }
    return jsonify(response)

papapt/views/schedule.py
# coding: utf-8
import calendar
from flask import Blueprint, render_template, current_app, request, abort
from collections import defaultdict
from datetime import date
from ..models import Schedule


ustv = Blueprint('ustv', __name__)


@ustv.route('/ustv')
def schedule():
    app_year = current_app.config['SCHEDULE_CURRENT_YEAR']
    app_month = current_app.config['SCHEDULE_CURRENT_MONTH']
    year = request.args.get('y', app_year, type=int)
    month = request.args.get('m', app_month, type=int)
    title_lang = request.args.get('l', 'e')

    if (app_year - 1 <= year <= app_year + 1 and 0 < month < 13 or
        year == app_year and month < app_month + 2) \
            and title_lang in ['c', 'e']:

        start = get_isoformat(year, month, 1)
        if month == 12:
            end = get_isoformat(year + 1, 1, 1)
        else:
            end = get_isoformat(year, month + 1, 1)

        month_rows = Schedule.query.\
            filter(Schedule.air_date.between(start, end)).\
            order_by(Schedule.air_date).\
            all()

        month_cal = calendar.monthcalendar(year, month)

        after_group = group_by_day(month_rows)
        return render_template(
                        'tv.html',
                        cal=month_cal,
                        rows=after_group,
                        lang=title_lang,
                        month=month,
                        year=year)
    else:
        abort(404)


def get_isoformat(year, month, day):
    return date(year, month, day).isoformat()


def group_by_day(month_rows):
    month = defaultdict(list)
    for r in month_rows:
        month[r.air_date.day].append(r)
    return dict(month)


@ustv.app_template_filter(name='dayofweek')
def day_of_week(day_index, lang='chs'):
    weekdays = {
        'eng': ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
        'chs': [u"周一", u"周二", u"周三", u"周四", u"周五", u"周六", u"周日"]
        }
    return weekdays[lang][day_index]

papapt/views/search.py
# coding: utf-8
import re
from flask import Blueprint, current_app, render_template, request
from sqlalchemy import or_
from datetime import datetime
from ..models import Torrent


search = Blueprint('search', __name__)


@search.route('/search/<path:keyword>')
def result(keyword):
    mix_keyword = strip_and_replace(keyword)

    if mix_keyword == '%%':  # invaild
        return render_template('result.html', keyword=keyword)
    else:
        page = request.args.get('page', 1, type=int)
        order_by = request.args.get('order')
        sort_way = request.args.get('sort', 'des')
        cat = request.args.get('cat')  # torrent category

        title_like = or_(
                    Torrent.t_d_title.like(mix_keyword),
                    Torrent.t_u_title.like(mix_keyword))

        q = Torrent.query.filter(title_like)

        cat_count = {}
        if q.count() < current_app.config['CAT_COUNT_LIMIT_MAX_ITEM']:
            cat_count = count_torrents_cat(q)

        if order_by:
            order_attr = getattr(Torrent, order_by)
            if sort_way == 'asc':
                q = q.order_by(order_attr)
            else:
                q = q.order_by(order_attr.desc())

        if cat:
            q = q.filter(Torrent.t_recat == cat)

        q_pagination = q.paginate(page, current_app.config['ITEM_PER_PAGE'])
        rows = q_pagination.items

        return render_template(
                        'result.html',
                        keyword=keyword,
                        results=rows,
                        pagination=q_pagination,
                        counts=cat_count)


def count_torrents_cat(query):
    count_dict = {}
    for t in query.all():
        count_dict[t.t_recat] = count_dict.get(t.t_recat, 0) + 1
    return count_dict


def strip_and_replace(keyword):  # extract chs, eng, num char
    k = re.sub(u'[^\u4e00-\u9fa5a-zA-Z0-9]+', ' ', keyword)  # other to ' '
    k = '%' + "%".join(k.split()) + '%'  # ' ' to %
    return k


@search.app_template_filter(name='chstime')
def chs_time(dt, future_=u"穿越?", default=u"刚刚"):
    now = datetime.now()
    if now > dt:
        diff = now - dt
        dt_is_past = True
    else:
        diff = dt - now
        dt_is_past = False

    periods = (
        (diff.days / 365, u"年"),
        (diff.days / 30, u"月"),
        (diff.days / 7, u"周"),
        (diff.days, u"天"),
        (diff.seconds / 3600, u"时"),
        (diff.seconds / 60, u"分"),
        (diff.seconds, u"秒"),
    )

    if dt_is_past:
        for period, chs_period in periods:
            if period:
                return "%d%s" % (period, chs_period)
    else:
        return future_
    return default


@search.app_template_filter(name='chscat')
def chs_cat(cat_key):
    cat = {
        'bd': u'原盘',
        'mov': u'电影',
        'eustv': u'欧美剧',
        'eustvp': u'欧美剧包',
        'cntv': u'华语剧',
        'cntvp': u'华语剧包',
        'jktv': u'日韩剧',
        'jktvp': u'日韩剧包',
        'mob': u'移动格式',
        'spo': u'体育',
        'ami': u'动漫',
        'var': u'综艺',
        'mus': u'音乐',
        'doc': u'纪录片',
        'other': u'其它',
    }
    return cat.get(cat_key, u'未知')


@search.app_template_filter(name='defi')
def get_defi(defi_key):
    defi = {
        1: u'不明',
        3: '720p',
        5: '1080i',
        7: '1080p',
        8: 'BD',
        9: 'BD'
    }
    return defi.get(defi_key, u'不明')

papapt/views/timeline.py
from flask import Blueprint, render_template, request
from ..models import Torrent


timeline = Blueprint('timeline', __name__)


@timeline.route('/timeline')
def pages():
    page = request.args.get('page', 1, type=int)
    query = Torrent.query.order_by(Torrent.t_addtime.desc())
    q_pagination = query.paginate(page, 20)
    page_items = q_pagination.items
    return render_template('timeline.html', rows=page_items, current_page=page)

papapt/views/top.py
from flask import Blueprint, render_template, request, abort
from ..models import Top


top = Blueprint('top', __name__)


@top.route('/top250')
def top_rank():
    site = request.args.get('site')
    page = request.args.get('page', 1, type=int)
    items_each_page = 25
    if site in ['imdb', 'douban'] and 0 < page < 11:
        end = page * items_each_page
        start = end - items_each_page + 1
        result = Top.query.filter(Top.rank.between(start, end))
        return render_template('top.html', site=site, result=result.all())
    else:
        abort(404)

papapt/templates/base.html
{%- extends "bootstrap/base.html" %}
{%- block metas -%}
{%- endblock -%}
{% block head %}
  {{super()}}
  <link rel="icon" type="image/png" href="{{ url_for('home.static', filename='favicon.png') }}">
{% endblock %}
{%- block title %}papapt{% endblock %}
{% block styles -%}
    {{super()}}  {# do not forget to call super or Bootstrap's own stylesheetswill disappear! #}
    <link rel="stylesheet" type="text/css" href="{{ url_for('home.static', filename='new.css') }}">
{%- endblock %}
{# Finally, round things out with navigation #}
{% block navbar -%}
<div class="navbar navbar-default">
  <div class="container col-md-10 col-md-offset-1">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">papapt</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('home.index') }}">首页</a></li>
      <li><a href="{{ url_for('timeline.pages') }}">最新采集</a></li>
      <li><a href="{{ url_for('ustv.schedule', y=config.SCHEDULE_CURRENT_YEAR, m=config.SCHEDULE_CURRENT_MONTH, l='e') }}">美剧时间表</a></li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">TOP250
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{{ url_for('top.top_rank', site='douban') }}">豆瓣</a></li>
          <li><a href="{{ url_for('top.top_rank', site='imdb') }}">IMDb</a></li>
        </ul>
      </li>
      </ul>
        {%- if request.url_rule.endpoint != 'home.index' %}
          <form class="navbar-form navbar-right nav-search" method="POST" action="/search_query">
            <div class="input-group">
              {{ g.search_form.hidden_tag() }}
              {{ g.search_form.search(class_="form-control") }}
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </span>
            </div>
          </form>
        {% endif -%}
  </div>
</div>
{%- endblock %}

papapt/templates/byid_macros.html
{%- macro create_id_url(website, id) %}
    {%- if website == 'imdb' %}
        <a href="http://www.imdb.com/title/{{ id }}/" target="_blank"><mark>{{ id }}</mark></a>
    {%- else -%}
        <a href="https://movie.douban.com/subject/{{ id }}/" target="_blank"><mark>{{ id }}</mark></a>
    {% endif -%}
{% endmacro -%}

papapt/templates/index.html
{%- extends "base.html" %}
{%- block content %}
<div class="container col-md-10 col-md-offset-1">
        <div class='col-md-6 flash-header'>
            {%- with messages = get_flashed_messages() %}
            {%- if messages %}
              {% for message in messages -%}
                <div class="alert alert-danger flashes">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
              {%- endfor %}
              </div>
            {%- endif %}
          {%- endwith %}
        </div>
        <div class="col-md-10 col-md-offset-1">
            <form class="index-search" method="POST" action=" {{ url_for('home.search') }}">
                <div class="input-group">
                    {{ g.search_form.hidden_tag() }}
                    {{ g.search_form.search(class_="form-control", placeholder="可以直接放IMDb和豆瓣链接哦") }}
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="sumbit">给我搜</button>
                    </span>
                </div>
            </form>
            <div class="col-md-10 col-md-offset-1 hot-keyword">
              <div class="keyword-item">
                <span style="vertical-align: text-top; padding-right: 1px;" class="text-danger glyphicon glyphicon-fire"></span><span class="text-danger">热门：</span>
              </div>
                {% for r in rows -%}
                  {%- set k_type = r.keyword_type -%}
                  {%- set k = r.keyword -%}
                  {%- if k_type == 'douban' or k_type == 'imdb' %}
                    <div class="keyword-item">
                      <span><a class="text-muted" style="text-decoration: none;" href="{{ url_for('rating.by_site_id', website=k_type, site_id=k)}}">{{ r[k_type].title }}</a></span>
                    </div>
                  {%- else -%}
                    <div class="keyword-item">
                      <span><a class="text-muted" style="text-decoration: none;" href="{{ url_for('search.result', keyword=k) }}">{{ k }}</a></span>
                    </div>
                  {% endif -%}
                {%- endfor %}
              <p
            </div>
        </div>
</div>
{% endblock -%}

papapt/templates/timeline.html
{%- from "timeline_macros.html" import create_class_by_from %}
{%- extends "base.html" %}
{%- block title %}
    最新采集 - papapt
{% endblock -%}
{%- block content %}
    <div class="container">
        <div>
        <ul class="timeline">
            {% for r in rows -%}
            <li>
                <div class="timeline-t-from">
                {%- set t_from = r.t_from[:1] -%}
                {%- set class = 'span-tooltip btn btn-tl-copy' -%}
                <button title="复制文件名" last-tooltip="nothere" class="{{ class + ' ' + create_class_by_from(t_from) }}">{{ t_from|upper }}</button>
                </div>
                <div class="timeline-t-wrap">
                    <div class="timeline-t-info">
                        <p class="timeline-t-title"><strong><span class="span-tooltip" title="{{ r.t_d_title }}">{{ r.t_u_title }}</span></strong></p>
                        <p class="timeline-t-detail">
                        <span class="text-info tl-cat">{{ r.t_recat|chscat }}</span>
                        <span class="tl-size">{{ (r.t_size/1024)|round(1) }}<span class="text-muted">GB</span></span>
                        <span class="span-tooltip tl-addtime" title="{{ r.t_addtime }}">{{ r.t_addtime|chstime }}</span>
                        <span class="tl-defi text-muted">{{ r.t_defi|defi }}</span>
                        </p>
                    </div>
                </div>
            </li>
            {%- endfor %}
        </ul>
        </div>
    </div>
    <div class="nextpage">
        <a href="{{ url_for('timeline.pages', page=current_page+1) }}"></a>
    </div>
{% endblock -%}
{%- block scripts %}
    {{super()}}
    <script src="https://cdn.bootcss.com/jquery-infinitescroll/2.1.0/jquery.infinitescroll.min.js"></script>
    <script src="https://cdn.bootcss.com/clipboard.js/1.5.10/clipboard.min.js"></script>
    <script>
        function tl_helper(){$(".span-tooltip").tooltip({animated:"fade",placement:"bottom",container:"body"});var t=new Clipboard(".btn-tl-copy",{text:function(t){return $(t).parent().parent().find(".timeline-t-title").text()}});t.on("success",function(t){$("[last-tooltip=here]").attr("title","复制文件名").tooltip("fixTitle"),$("[last-tooltip=here]").attr("last-tooltip","nothere"),$(t.trigger).attr("title","已复制文件名").tooltip("fixTitle").tooltip("show"),$(t.trigger).attr("last-tooltip","here")})}$(document).ready(function(){$(".timeline").infinitescroll({navSelector:"div.nextpage",nextSelector:"div.nextpage a:last",itemSelector:"ul.timeline",maxPage:{{ config.TIMELINE_MAX_PAGE }},bufferPx:5,extraScrollPx:50,loading:{speed:"fast",selector:null,img:"data:image/gif;base64,R0lGODlhAQABAHAAACH5BAUAAAAALAAAAAABAAEAAAICRAEAOw==",msgText:"",finishedMsg:'<div class="max-page-reach text-muted"><h3>你已经看完最新的种子了</h3></div>'}},function(){tl_helper()}),tl_helper()});
    </script>
{% endblock -%}

papapt/templates/top_macros.html
{%- macro create_top_pager(which_way) %}
    {%- set site = request.args.site -%}
    {%- if request.args.page %}
        {%- set page = request.args.page|int -%}
    {%- else -%}
        {%- set page = 1 -%}
    {% endif -%}
    {%- if which_way == 'prev' %}
        {%- set span_arrow = '&laquo;' -%}
        {%- set expect_page = page - 1 -%}
    {% elif which_way == 'next' -%}
        {%- set span_arrow = '&raquo;' -%}
        {%- set expect_page = page + 1 -%}
    {% endif -%}
    {%- if which_way == 'prev' and page == 1 or which_way == 'next' and page == 10 %}
    <li class="disabled">
      <a href="#">
        <span aria-hidden="true">{{ span_arrow|safe }}</span>
      </a>
    </li>
    {%- else -%}
    <li>
      <a href="{{ url_for('top.top_rank', site=site, page=expect_page) }}">
        <span aria-hidden="true">{{ span_arrow|safe }}</span>
      </a>
    </li>
    {% endif -%}
{% endmacro -%}

{%- macro create_top_page_index(expect_page) -%}
    {%- set site = request.args.site -%}
    {%- if request.args.page %}
        {%- set page = request.args.page|int -%}
    {%- else -%}
        {%- set page = 1 -%}
    {% endif -%}
        {%- if page != expect_page %}
            <li><a href="{{ url_for('top.top_rank', site=site, page=expect_page) }}">{{ expect_page }}</a></li>
        {%- elif page == expect_page %}
            <li class="active"><a href="#">{{ expect_page }}</a><li>
        {%- endif -%}
{%- endmacro -%}

papapt/templates/tv_macros.html
{%- macro create_id_url(website, id) %}
    {%- if website == 'imdb' -%}
        {%- set link = 'http://www.imdb.com/title/' + id|string -%}
        {%- set site = 'IMDb' -%}
    {%- else -%}
        {%- set link = 'https://movie.douban.com/subject/' + id|string -%}
        {%- set site = '豆瓣' -%}
    {%- endif -%}
        <a style="text-decoration: none;" href="{{ link }}" target="_blank">{{ site }}</a>
{% endmacro -%}

{%- macro create_day_div(day, db_rows, day_index, title_lang) -%}
    {% if not day -%}
        {{ create_empty_day() }}
    {%- else -%}
        <div class="day">
            <div class="day-header">
                <span class="day-num">{{ day }}</span>
                <span class="chs-dow">{{ day_index|dayofweek }}</span>
                <div style="clear: both"></div>
            </div>
            {%- if db_rows %}
                {% for r in db_rows -%}
                    <div class="show-info">
                    {%- set eng_title = r.tv.title -%}
                    {%- set s_e = 'S' + '%02d' % r.season + 'E' + '%02d' % r.episode -%}
                    <p class="show-title" >
                        <a href="{{ url_for('search.result', keyword=eng_title) }}"><strong>{{ r.tv[title_lang] }}</strong></a>
                    </p>
                    <p class="show-episode">
                        <span>
                            <a style="text-decoration: none;" class="a-tooltip" title="{{ r.air_date.strftime('%H:%M') + ' 开始播放' + ' 时长 ' + r.tv.runtime|string + ' 分钟' }}" href="{{ url_for('search.result', keyword=eng_title + ' ' + s_e) }}">{{ s_e }}</a>
                        </span>
                        <span class="hover-show">
                            {{ create_id_url('douban', r.tv.douban) }}
                            {{ create_id_url('imdb', r.tv.imdb) }}
                        </span>
                    </p>
                    </div>
                {%- endfor %}
            {% endif -%}
        </div>
    {%- endif %}
{%- endmacro -%}

{%- macro create_week_div(days_of_week, title_lang) %}
    <div class="week">
        {%- for day in days_of_week -%}
            {{ create_day_div(day, rows.get(day), loop.index0, title_lang) }}
        {% endfor -%}
    </div>
{%- endmacro -%}

{%- macro create_empty_day() -%}
    {{ '<div class="empty-day"></div>'|safe }}
{%- endmacro -%}

{%- macro create_ustv_pager(text=false) %}
    {%- set current_year = config.SCHEDULE_CURRENT_YEAR -%}
    {%- set current_month = config.SCHEDULE_CURRENT_MONTH -%}

    {%- if year == current_year and month == 1 %}
        {%- set last_month = 12 -%}
        {%- set next_month = month + 1 -%}
        {%- set last_year = current_year - 1 -%}
        {%- set next_year = year -%}
    {% elif year == current_year - 1 and month == 12 -%}
        {%- set last_month = 11 -%}
        {%- set next_month = 1 -%}
        {%- set last_year = year -%}
        {%- set next_year = current_year -%}
    {% elif year == current_year and month == 12 -%}
        {%- set last_month = 12 -%}
        {%- set next_month = 1 -%}
        {%- set last_year = current_year -%}
        {%- set next_year = current_year + 1 -%}
    {%- else -%}
        {%- set last_month = month - 1 -%}
        {%- set next_month = month + 1 -%}
        {%- set last_year = year -%}
        {%- set next_year = year -%}
    {% endif -%}
    <div class="ustv-pager">
        <div class="pager-left">
            <a href="{{ url_for('ustv.schedule', y=last_year, m=last_month, l=lang) if year == current_year - 1 and month != 1 or year == current_year else '#' }}">
                <button type="button" class="ustv-left-btn btn btn-default{{ ' disabled' if year == current_year - 1 and month == 1 }}">&laquo; 上月</button>
            </a>
        </div>
        {%- if text %}
            <div class="pager-header">
                <span class="header-text"><strong>{{ year }}年{{ month }}月</strong>
                {%- set lang_switch = {'e':'c', 'c':'e'} -%}
                    <a class="a-tooltip" style="text-decoration: none" data-html="true" title="点我切换中英剧名<br>点剧名搜全部<br>点集数搜单集<br>以下为北京时间" href="{{ url_for('ustv.schedule', y=year, m=month, l=lang_switch[lang]) }}">
                        <span style="vertical-align: top;" class="text-warning glyphicon glyphicon-exclamation-sign"></span>
                    </a>
            </div>
        {% endif -%}
        <div class="pager-right">
            <a href="{{ url_for('ustv.schedule', y=next_year, m=next_month, l=lang) if year == current_year - 1 or year == current_year and month < current_month + 1 else '#' }}">
                <button type="button" class="ustv-right-btn btn btn-default{{ ' disabled' if year == current_year and month == current_month + 1 }}">下月 &raquo;</button>
            </a>
        </div>
        {%- if not text %}
            <div style="padding-bottom: 50px;"></div>
        {% endif -%}
    </div>
{% endmacro -%}